[package]
name = "mini_grep"
version = "0.0.0"
edition = "2021"
authors = ["Amadou Traore"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
